# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-12 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='certificate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='distinguishedname',
            table=None,
        ),
    ]
