# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 06:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='shortname',
            field=models.CharField(default='repleo', editable=False, help_text='Short name used to store your keys and scripts.', max_length=128, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\_\\.]*$', 'Only alphanumeric characters and [_.] are allowed.')]),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(help_text='Long name of your authority, if not set will be equal to your CommonName.', max_length=128, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ ]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')]),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='parent',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='x509_pki.Certificate'),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='commonName',
            field=models.CharField(default='*.repleo.nl', editable=False, help_text='The fully qualified domain name (FQDN) of your server. This must match exactly what you type in your web browser or you will receive a name mismatch error.', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')]),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='emailAddress',
            field=models.EmailField(default='ca@repleo.nl', editable=False, help_text='An email address used to contact your organization.', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')]),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='localityName',
            field=models.CharField(default='Amstelveen', editable=False, help_text='The city where your organization is located. The locality is 1–128 characters.', max_length=128, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')]),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='organizationName',
            field=models.CharField(default='Repleo', editable=False, help_text='The legal name of your organization. This should not be abbreviated and should include suffixes such as Inc, Corp, or LLC.', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')]),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='organizationalUnitName',
            field=models.CharField(default='IT Department', editable=False, help_text='The division of your organization handling the certificate.', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')]),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='stateOrProvinceName',
            field=models.CharField(default='Noord Holland', editable=False, help_text="The state/region where your organization is located. This shouldn't be abbreviated. The stateorprov is 1–128 characters.", max_length=128, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')]),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together=set([('shortname', 'type')]),
        ),
    ]
