# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-13 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0002_auto_20180612_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='serial',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
