# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 07:17
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0002_auto_20160505_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 5, 7, 17, 7, 174974, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='expires_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 5, 7, 17, 11, 791632, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='commonName',
            field=models.CharField(default='*.repleo.nl', help_text='The fully qualified domain name (FQDN) of your server. This must match exactly what you type in your web browser or you will receive a name mismatch error.', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')]),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='emailAddress',
            field=models.EmailField(default='ca@repleo.nl', help_text='An email address used to contact your organization.', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')]),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='localityName',
            field=models.CharField(default='Amstelveen', help_text='The city where your organization is located. The locality is 1–128 characters.', max_length=128, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')]),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='organizationName',
            field=models.CharField(default='Repleo', help_text='The legal name of your organization. This should not be abbreviated and should include suffixes such as Inc, Corp, or LLC.', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')]),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='organizationalUnitName',
            field=models.CharField(default='IT Department', help_text='The division of your organization handling the certificate.', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')]),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='stateOrProvinceName',
            field=models.CharField(default='Noord Holland', help_text="The state/region where your organization is located. This shouldn't be abbreviated. The stateorprov is 1–128 characters.", max_length=128, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')]),
        ),
    ]
