# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-16 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0003_certificate_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='revoked_at',
            field=models.DateField(blank=True, default=None, editable=False, null=True),
        ),
    ]
