# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0004_auto_20160505_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='expires_at',
            field=models.DateField(help_text='Select the date that the certificate will expire: for root typically 20 years, for intermediate 10 years for other types 1 year.'),
        ),
    ]
