# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-17 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0004_auto_20180616_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='crt',
            field=models.TextField(default=b'', verbose_name='Serialized signed certificate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='key',
            field=models.TextField(default=b'', verbose_name='Serialized Private Key'),
            preserve_default=False,
        ),
    ]
