# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 10:20
from __future__ import unicode_literals

import bounca.x509_pki.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0005_auto_20160505_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='expires_at',
            field=models.DateField(help_text='Select the date that the certificate will expire: for root typically 20 years, for intermediate 10 years for other types 1 year.', validators=[bounca.x509_pki.models.validate_in_future]),
        ),
    ]
