# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-17 12:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0005_auto_20180617_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distinguishedname',
            name='countryName',
            field=django_countries.fields.CountryField(help_text='The two-character country name in ISO 3166 format.', max_length=2, verbose_name='Country Name'),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='localityName',
            field=models.CharField(help_text='The city where your organization is located. (1–128 characters)', max_length=128, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')], verbose_name='Locality Name'),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='organizationName',
            field=models.CharField(help_text='The legal name of your organization. This should not be abbreviated and should include suffixes such as Inc, Corp, or LLC.', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')], verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='organizationalUnitName',
            field=models.CharField(help_text='The division of your organization handling the certificate.', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')], verbose_name='Organization Unit Name'),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='stateOrProvinceName',
            field=models.CharField(help_text="The state/region where your organization is located. This shouldn't be abbreviated. (1–128 characters)", max_length=128, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')], verbose_name='State or Province Name'),
        ),
    ]
