# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0006_auto_20160505_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
