# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0007_auto_20160505_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='type',
            field=models.CharField(choices=[('R', 'Root CA Certificate'), ('I', 'Intermediate CA Certificate'), ('S', 'Server Certificate'), ('C', 'Client Certificate'), ('O', 'OCSP Signing Certificate')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together=set([('shortname', 'type'), ('dn', 'type')]),
        ),
    ]
