# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0008_auto_20160507_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='crl_distribution_url',
            field=models.URLField(blank=True, help_text='Base URL for certificate revocation list (CRL)', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='ocsp_distribution_host',
            field=models.URLField(blank=True, help_text='Host URL for Online Certificate Status Protocol (OCSP)', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='revoked_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together=set([('dn', 'type', 'revoked_at'), ('shortname', 'type', 'revoked_at')]),
        ),
    ]
