# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 20:42
from __future__ import unicode_literals

import bounca.x509_pki.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0009_auto_20160507_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='expires_at',
            field=models.DateField(help_text='Select the date that the certificate will expire: for root typically 20 years, for intermediate 10 years for other types 1 year. Allowed date format: yyyy-mm-dd.', validators=[bounca.x509_pki.models.validate_in_future]),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(blank=True, help_text='Long name of your key, if not set will be equal to your shortname + CommonName.', max_length=128, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ ]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')]),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The signing authority (None for root certificate)', null=True, on_delete=django.db.models.deletion.CASCADE, to='x509_pki.Certificate'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='shortname',
            field=models.CharField(help_text='Short name to identify your key.', max_length=128, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\_\\.]*$', 'Only alphanumeric characters and [_.] are allowed.')], verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='commonName',
            field=models.CharField(default='*.repleo.nl', help_text='The fully qualified domain name (FQDN) of your server. This must match exactly what you type in your web browser or you will receive a name mismatch error.', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')], verbose_name='Common Name'),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='countryName',
            field=django_countries.fields.CountryField(default='NL', help_text='The two-character country name in ISO 3166 format.', max_length=2, verbose_name='Country Name'),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='emailAddress',
            field=models.EmailField(default='ca@repleo.nl', help_text='The email address to contact your organization. Also used by BounCA for authentication.', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')], verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='localityName',
            field=models.CharField(default='Amstelveen', help_text='The city where your organization is located. (1–128 characters)', max_length=128, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')], verbose_name='Locality Name'),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='organizationName',
            field=models.CharField(default='Repleo', help_text='The legal name of your organization. This should not be abbreviated and should include suffixes such as Inc, Corp, or LLC.', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')], verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='organizationalUnitName',
            field=models.CharField(default='IT Department', help_text='The division of your organization handling the certificate.', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')], verbose_name='Organization Unit Name'),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='stateOrProvinceName',
            field=models.CharField(default='Noord Holland', help_text="The state/region where your organization is located. This shouldn't be abbreviated. (1–128 characters)", max_length=128, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')], verbose_name='State or Province Name'),
        ),
    ]
