# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0013_auto_20160510_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='revoked_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
