# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0014_auto_20160510_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='crl_distribution_url',
            field=models.URLField(blank=True, help_text='Base URL for certificate revocation list (CRL)', null=True, verbose_name='CRL distribution url'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='ocsp_distribution_host',
            field=models.URLField(blank=True, help_text='Host URL for Online Certificate Status Protocol (OCSP)', null=True, verbose_name='OCSP distribution host'),
        ),
    ]
