# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0015_auto_20160515_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='revoked_uuid',
            field=models.UUIDField(default='00000000000000000000000000000001'),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together=set([('shortname', 'type', 'revoked_uuid'), ('dn', 'type', 'revoked_uuid')]),
        ),
    ]
