# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 06:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0017_auto_20160515_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='distinguishedname',
            name='subjectAltName',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')]), blank=True, help_text='subjectAltName list', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='commonName',
            field=models.CharField(help_text='The fully qualified domain name (FQDN) of your server. This must match exactly what you type in your web browser or you will receive a name mismatch error.', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')], verbose_name='Common Name'),
        ),
    ]
