# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 10:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0021_auto_20160520_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distinguishedname',
            name='subjectAltNames',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')]), blank=True, help_text='subjectAltName list, i.e. dns names for server certs and email adresses for client certs. (separate by comma)', null=True, size=None),
        ),
    ]
