# Generated by Django 4.0.4 on 2022-04-18 08:22

from django.db import migrations, models

from certificate_engine.ssl.info import get_certificate_fingerprint


def set_my_defaults(apps, schema_editor):
    Keystore = apps.get_model('x509_pki', 'keystore')
    for keystore in Keystore.objects.all().iterator():
        keystore.fingerprint = get_certificate_fingerprint(keystore.crt)
        keystore.save()


def reverse_func(apps, schema_editor):
    pass  # code for reverting migration, if any


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0001_squashed_0015_keystore_p12'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystore',
            name='fingerprint',
            field=models.TextField(null=True, verbose_name='SHA1 Fingerprint of Certificate'),
            preserve_default=False,
        ),
        migrations.RunPython(set_my_defaults, reverse_func),
        migrations.AlterField(
            model_name='keystore',
            name='fingerprint',
            field=models.TextField(),
        ),
    ]

