# Generated by Django 3.0.8 on 2020-07-27 08:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('x509_pki', '0002_auto_20200719_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='dn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='x509_pki.DistinguishedName'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The signing authority (None for root certificate)', null=True, on_delete=django.db.models.deletion.PROTECT, to='x509_pki.Certificate'),
        ),
        migrations.AlterField(
            model_name='distinguishedname',
            name='emailAddress',
            field=models.EmailField(blank=True, help_text='The email address to contact your organization. Also used by BounCA for authentication.', max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ \\*]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')], verbose_name='Email Address'),
        ),
    ]
