# Generated by Django 4.0.4 on 2022-05-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0002_keystore_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystore',
            name='fingerprint',
            field=models.TextField(verbose_name='SHA1 Fingerprint of Certificate'),
        ),
    ]
