# Generated by Django 3.0.8 on 2020-10-02 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0003_auto_20200727_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(blank=True, help_text='Name of your key, if not set will be equal to your CommonName.', max_length=128, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@#$%^&+=\\_\\.\\-\\,\\ ]*$', 'Only alphanumeric characters and [@#$%^&+=_,-.] are allowed.')]),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('dn', 'type', 'revoked_uuid'), ('name', 'type', 'revoked_uuid')},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='shortname',
        ),
    ]
