# Generated by Django 4.0.4 on 2022-05-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0003_alter_keystore_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='type',
            field=models.CharField(choices=[('R', 'Root CA Certificate'), ('I', 'Intermediate CA Certificate'), ('S', 'Server Certificate'), ('C', 'Client Certificate'), ('D', 'Code Signing Certificate'), ('O', 'OCSP Signing Certificate')], max_length=1),
        ),
    ]
