# Generated by Django 4.1.5 on 2023-02-05 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("x509_pki", "0004_alter_certificate_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="crl_distribution_url",
            field=models.URLField(
                blank=True,
                help_text="Base URL for certificate revocation list (CRL)",
                null=True,
                validators=[
                    django.core.validators.RegexValidator("[^\\/]\\.crl$", "CRL url should end with <filename>.crl")
                ],
                verbose_name="CRL distribution url",
            ),
        ),
    ]
