# Generated by Django 3.1.3 on 2020-11-14 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0004_auto_20201002_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='crt',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='key',
        ),
        migrations.CreateModel(
            name='KeyStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(verbose_name='Serialized Private Key')),
                ('crt', models.TextField(verbose_name='Serialized signed certificate')),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='x509_pki.certificate')),
            ],
        ),
    ]
