# Generated by Django 3.1.3 on 2020-11-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0005_auto_20201114_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystore',
            name='crt',
            field=models.BinaryField(verbose_name='Serialized signed certificate'),
        ),
        migrations.AlterField(
            model_name='keystore',
            name='key',
            field=models.BinaryField(verbose_name='Serialized Private Key'),
        ),
    ]
