# Generated by Django 4.2.9 on 2024-01-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("x509_pki", "0005_alter_certificate_crl_distribution_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="keystore",
            name="p12_legacy",
            field=models.BinaryField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Serialized PKCS 12 package with key and certificate sha1 for legacy support",
            ),
        ),
    ]
