# Generated by Django 3.1.3 on 2020-11-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0006_auto_20201114_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystore',
            name='crt',
            field=models.TextField(verbose_name='Serialized signed certificate'),
        ),
        migrations.AlterField(
            model_name='keystore',
            name='key',
            field=models.TextField(verbose_name='Serialized Private Key'),
        ),
    ]
