# Generated by Django 3.2.7 on 2021-10-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0008_auto_20211016_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='crl',
        ),
        migrations.AddField(
            model_name='keystore',
            name='crl',
            field=models.TextField(blank=True, null=True, verbose_name='Serialized CRL certificate'),
        ),
    ]
