# Generated by Django 3.2.7 on 2021-10-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0010_auto_20211017_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='revoked_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
