# Generated by Django 3.2.7 on 2021-10-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0011_alter_certificate_revoked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='crlstore',
            name='last_update',
            field=models.DateTimeField(auto_now=True, help_text='Date at which last crl has been generated'),
        ),
    ]
