# Generated by Django 3.2.9 on 2021-12-03 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0012_crlstore_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='crl_distribution_url',
            field=models.URLField(blank=True, help_text='Base URL for certificate revocation list (CRL)', null=True, validators=[django.core.validators.RegexValidator('[^\\/]\\.crl\\.pem$', 'CRL url shoud end with <filename>.crl.pem')], verbose_name='CRL distribution url'),
        ),
    ]
