# Generated by Django 3.2.9 on 2021-12-04 21:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('x509_pki', '0013_alter_certificate_crl_distribution_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('dn', 'type', 'revoked_uuid'), ('name', 'owner', 'type', 'revoked_uuid')},
        ),
    ]
