# Generated by Django 3.2.9 on 2021-12-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x509_pki', '0014_alter_certificate_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystore',
            name='p12',
            field=models.BinaryField(blank=True, default=None, null=True, verbose_name='Serialized PKCS 12 package with key and certificate'),
        ),
    ]
