# Generated by Django 4.0.4 on 2022-05-26 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('x509_pki', '0004_alter_certificate_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(choices=[('RCRL', 'Read CRL of root and intermediate certificates'), ('RCERT', 'Read root and intermediate certificates'), ('RISSUED', 'Read issued certificates, including private key')], max_length=7)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='x509_pki.certificate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner', 'certificate', 'access'],
                'unique_together': {('owner', 'access', 'certificate')},
            },
        ),
        migrations.CreateModel(
            name='AuthorisedApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('token', models.TextField(unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('scopes', models.ManyToManyField(to='api.scope')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
