# Generated by Django 4.0.4 on 2022-05-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorisedapp',
            name='scopes',
        ),
        migrations.DeleteModel(
            name='Scope',
        ),
    ]
