# Generated by Django 4.0.4 on 2022-06-18 22:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_rename_owner_authorisedapp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorisedapp',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='authorisedapp',
            unique_together={('name', 'user')},
        ),
    ]
